# Generated by Django 5.1.6 on 2025-02-25 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleto',
            name='arquivo_pdf',
            field=models.FileField(blank=True, null=True, upload_to='boletos/'),
        ),
    ]
