# Generated by Django 5.1.6 on 2025-03-26 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_cliente_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('venda', 'Contrato de Venda'), ('locacao', 'Contrato de Locação')], max_length=10)),
                ('descricao', models.TextField()),
                ('data', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
