# Generated by Django 5.1.6 on 2025-03-26 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_contrato'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='data',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='descricao',
        ),
        migrations.AddField(
            model_name='contrato',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='contratos/'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='tipo',
            field=models.CharField(choices=[('venda', 'Venda'), ('locacao', 'Locação')], max_length=20),
        ),
    ]
