# Generated by Django 5.1.6 on 2025-03-27 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_remove_contrato_cliente_remove_contrato_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='nome',
            field=models.CharField(default='Contrato Padrão', max_length=255),
        ),
    ]
