# Generated by Django 5.1.6 on 2025-03-27 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_contrato_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
