# Generated by Django 5.1.6 on 2025-03-31 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_ordemcontrato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemcontrato',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado')], default='pendente', max_length=20),
        ),
        migrations.AlterField(
            model_name='ordemcontrato',
            name='tipo',
            field=models.CharField(max_length=100),
        ),
    ]
