# Generated by Django 5.1.6 on 2025-04-01 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0008_alter_ordemcontrato_status_alter_ordemcontrato_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemcontrato',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ordemcontrato',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('concluido', 'Concluído')], default='pendente', max_length=10),
        ),
    ]
