# Generated by Django 5.1.6 on 2025-04-01 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0010_ordemcontrato_etapa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemcontrato',
            name='etapa',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
