# Generated by Django 5.1.6 on 2025-04-03 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0012_alter_ordemcontrato_nome_alter_ordemcontrato_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etapacontrato',
            name='numero',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
