# Generated by Django 5.1.6 on 2025-04-07 19:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0013_alter_etapacontrato_numero'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='etapacontrato',
            name='numero',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='etapacontrato',
            unique_together={('numero', 'usuario')},
        ),
    ]
