# Generated by Django 5.1.6 on 2025-04-10 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0016_alter_faseprocesso_options_alter_faseprocesso_numero'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemFaseProcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='itens_fase/')),
                ('fase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='clientes.faseprocesso')),
            ],
        ),
    ]
