# Generated by Django 5.1.6 on 2025-04-10 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0017_itemfaseprocesso'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemcontrato',
            name='tipo_envio',
            field=models.CharField(choices=[('visualizacao', 'Somente Visualização'), ('envio', 'Envio pelo Usuário')], default='envio', max_length=20),
        ),
    ]
